export const SET_HOSTNAME = 'SET_HOSTNAME';
export const SET_IP_ADDRESS = 'SET_IP_ADDRESS';
export const SET_MTU = 'SET_MTU';
export const SET_SUBNETMASK = 'SET_SUBNETMASK';

export const SUCCESS_SET_HOSTNAME = 'SUCCESS_SET_HOSTNAME';
export const SUCCESS_SET_IP_ADDRESS = 'SUCCESS_SET_IP_ADDRESS';
export const SUCCESS_SET_MTU = 'SUCCESS_SET_MTU';
export const SUCCESS_SET_SUBNETMASK = 'SUCCESS_SET_SUBNETMASK';

export const LOCAL_NETWORK_PATH_SUFFIX = 'local_network/';