export const SET_DOMAIN_NAME = 'SET_DOMAIN_NAME';
export const SET_LEASE_TIME = 'SET_LEASE_TIME';
export const SET_BEGIN_IP_RANGE = 'SET_BEGIN_IP_RANGE';
export const SET_END_IP_RANGE = 'SET_END_IP_RANGE';
export const GET_DHCP_CONFIG = 'GET_DHCP_CONFIG';

export const SUCCESS_SET_DOMAIN_NAME = 'SUCCESS_SET_DOMAIN_NAME';
export const SUCCESS_SET_LEASE_TIME = 'SUCCESS_SET_LEASE_TIME';
export const SUCCESS_SET_BEGIN_IP_RANGE = 'SUCCESS_SET_BEGIN_IP_RANGE';
export const SUCCESS_SET_END_IP_RANGE = 'SUCCESS_SET_END_IP_RANGE';
export const SUCCESS_GET_DHCP_CONFIG = 'SUCCESS_GET_DHCP_CONFIG';

export const DHCP_PATH_SUFFIX = 'dhcp_config/';
