export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';

export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const SET_CREDENTIALS_SUCCESS = 'SET_CREDENTIALS_SUCCESS';
export const SET_CREDENTIALS_ERROR = 'SET_CREDENTIALS_ERROR';
